services:
  - type: web
    name: cafe-de-la-risa
    env: docker
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        value: base64:YjEtH8yycb+mPjcZR3aEjvPbwbQco1ZnWnkLA0F/l9I=
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/html/database/database.sqlite
      - key: GOOGLE_CLIENT_ID
        value: 105520060410-k9k9em48dkhdn4sm5glqsjo5narlto8a.apps.googleusercontent.com
      - key: GOOGLE_REDIRECT_URI
        value: https://cafe-de-la-risa.onrender.com/auth/google/callback
