services:
  - type: web
    name: cafe-de-la-risa
    env: docker
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        value: base64:YjEtH8yycb+mPjcZR3aEjvPbwbQco1ZnWnkLA0F/l9I=
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/html/database/database.sqlite
