<?php

return [
    "¿Por qué sacaron al perro del cine? Porque se metió.",
    "¿Qué le pasó al león que se comió un jabón? Ahora es puma.",
    "¿Cómo se llama el animal que come piedras y vuela? El come piedras volador.",
    "¿Qué tiene 5 dedos y no es tu pie? Mi pie.",
    "¿Qué dijo Bob el constructor cuando salió de su casa y no vio su camioneta? ¿Y mi camioneta?",
    "¿A dónde va Batman de vacaciones? A Batijuana.",
    "¿Qué hace una vaca en un escenario? Vacantar.",
    "Estaba estreñido y fui a Estados Unidos... ¿sabes a qué? A ver Chicago.",
    "Todo era gracioso hasta que supimos que el tartamudo quería decir jamón.",
    "Ayer fui a la gasolinería con Sharon. —¿Qué Sharon? —Gasolina.",
    "Había una vez un perro, llegó otro y ya habían dos.",
    "¿Qué tiene Woody en su celular? Un mensaje de voz.",
    "Checo Pérez con su mecánico: —Oye, por favor revisa mis llantas. —Sí, ahorita checo.",
    "¿De dónde viene Iron Man? Iron Know.",
    "¿Qué es verde y pica? Una rana con tenedor.",
    "¿Por qué el mar es azul? Porque los peces dicen blu blu blu.",
    "—Doctor, creo que soy alérgico al vino. —¿A qué vino? —A una consulta médica.",
    "¿Qué es un chiste que le pega a otro? Un chiste malo.",
    "La maestra dijo: 'Siéntense en silencio'... y Silencio murió aplastado.",
    "Había una piña colada... y la sacaron.",
    "Tengo un cuaderno de viaje, pero aún no vuelve.",
    "¿Sabes cuánta leche saca una vaca en su vida? La misma de bajada.",
    "Un pato quiere cruzar un puente con cartel que prohíbe pasar por arriba, abajo o nadando. ¿Cómo pasa? Como sea, no sabe leer.",
    "¿Cómo se llama un boomerang que no vuelve? Un palo.",
    "¿Dónde bailan los ciegos? En una pista de braille.",
    "¿Cómo se llaman las ciudades más pobres de Japón? Chin agua, Chin gas y Chin luz.",
    "¿Qué animal puede saltar más alto que una casa? Cualquiera, porque las casas no saltan.",
    "¿Qué pasa si un elefante se para en una pata? El pato se queda viudo.",
    "¿Cuál es el animal favorito de los atletas olímpicos? El loro.",
    "¿Sabes cómo le dicen a los deportistas en Veracruz? Aletas.",
    "¿Qué sonido hace una panadería cuando explota? PAAAN.",
    "¿Cuál es la fruta que sufre violencia doméstica? La papá yaa.",
    "¿Cuál es el número que no vende? El noventa.",
    "Le preguntaron a Jackie Chan sobre una dirección y contestó: ¡Jaaaaa!",
    "¿Sabes por qué los elefantes se pintan los huevos de rojo? Para esconderse en la mata de cerezas. ¿Has visto alguno? No. ¿Ves lo bien que se esconden?",
    "¿Te sabes el chiste del sordo y el distraído? —No. —¿Cómo?",
    "¿Cómo le dicen a un burro que vende sábanas? Un burrito sabanero.",
    "¿Dónde está la feria de Cepillín? En su cartera.",
    "El Temach si fuera un estómago: El stomach.",
    "Si el Temach fuera maestro de natación: ¡Mándela a la alberca, mi compa!",
    "Cuando le preguntas a tu amigo el DJ qué hay para beber: Agua agua agua xdd.",
    "¿Cuál es el colmo de Batman? Que lo Robin.",
    "Para ser Franco tendría que cambiarme el nombre.",
    "¿Saben por qué la ballena no se subió a la combi? Porque en el mar no hay combis.",
    "Un pato y un niño nacen a la vez, al cabo de un año ¿quién es mayor? El pato, porque tiene año y pico.",
    "A un gato le robaron su oro y ¿sabes qué dijo? MiAu miAu.",
    "¿Cómo murió? La golpearon con un violín, una guitarra y un bajo. Mmmm... todo concuerda.",
    "—¿Sabes qué me hace sonreír? —Awww ¿yo? —No, el nervio facial.",
    "¿Sabes cómo se llama el hermano perdido de Pinocho? Pinueve.",
    "Había un hombre tan pero tan fuerte que dobló la esquina.",
    "¿Sabes cuál es el árbol que asusta? El arbuuusto.",
    "¿Cómo se llaman las botas que se comen? Botanas.",
    "¿Qué le dijo una manzana a un cigarro? Nada porque no hablan.",
    "¿Qué le dijo una lata de atún a otra que estaba haciendo travesuras? Te voy a delatar.",
    "¿A dónde se van los billetes cansados? Al banco.",
    "¿Sabes por qué una jirafa toma más agua en marzo que en febrero? Porque marzo tiene más días.",
    "¿Qué le dijo un zapato travieso a otro? Ando desatado.",
    "¿Qué pasa si le pones maquillaje a un litro de gasolina? Se llamaría gasolinda.",
    "¿Por qué el pollo se arrojó al asador? Porque es el pollo loco.",
    "¿Cuál es el cable que te escucha? El de alta tensión.",
    "¿Por qué el caracol fue a la biblioteca? Porque está baboso.",
    "Una ardilla le dice a otra: A mí no me gustan las ardillas feas. —¡A chinga! ¿Por qué? —Es que me gustan las bellotas.",
    "¿Cómo le dice un libro a otro cuando salen de un problema? La libramos.",
    "¿Sabes por qué los golfistas usan dos pantalones? Por si tienen hoyo en uno.",
    "¿En qué se parece el tenis a Shrek? En que ambos tienen pelotas verdes.",
    "Si Batman es el caballero de la noche... ¿de día es un grosero?",
    "¿Cómo se dice náufrago en chino? Chin lancha."
];
