<?php

return [
    "¿Por qué sacaron al perro del cine? Porque se metió.",
    "¿Qué le pasó al león que se comió un jabón? Ahora es puma.",
    "¿Cómo se llama el animal que come piedras y vuela? El come piedras volador.",
    "¿Qué tiene 5 dedos y no es tu pie? Mi pie.",
    "¿Qué dijo Bob el constructor cuando salió de su casa y no vio su camioneta? ¿Y mi camioneta?",
    "¿A dónde va Batman de vacaciones? A Batijuana.",
    "¿Qué hace una vaca en un escenario? Vacantar.",
    "Estaba estreñido y fui a Estados Unidos... ¿sabes a qué? A ver Chicago.",
    "Todo era gracioso hasta que supimos que el tartamudo quería decir jamón.",
    "Ayer fui a la gasolinería con Sharon. —¿Qué Sharon? —Gasolina.",
    "Había una vez un perro, llegó otro y ya habían dos.",
    "¿Qué tiene Woody en su celular? Un mensaje de voz.",
    "Checo Pérez con su mecánico: —Oye, por favor revisa mis llantas. —Sí, ahorita checo.",
    "¿De dónde viene Iron Man? Iron Know.",
    "¿Qué es verde y pica? Una rana con tenedor.",
    "¿Por qué el mar es azul? Porque los peces dicen blu blu blu.",
    "—Doctor, creo que soy alérgico al vino. —¿A qué vino? —A una consulta médica.",
    "¿Qué es un chiste que le pega a otro? Un chiste malo.",
    "La maestra dijo: 'Siéntense en silencio'... y Silencio murió aplastado.",
    "Había una piña colada... y la sacaron.",
    "Tengo un cuaderno de viaje, pero aún no vuelve.",
    "¿Sabes cuánta leche saca una vaca en su vida? La misma de bajada.",
    "Un pato quiere cruzar un puente con cartel que prohibe pasar por arriba, abajo o nadando. ¿Cómo pasa? Como sea, no sabe leer.",
    "¿Cómo se llama un boomerang que no vuelve? Un palo.",
    "¿Dónde bailan los ciegos? En una pista de braille.",
    "¿Cómo se llaman las ciudades más pobres de Japón? Chin agua, Chin gas y Chin luz.",
    "¿Qué animal puede saltar más alto que una casa? Cualquiera, porque las casas no saltan.",
    "¿Qué pasa si un elefante se para en una pata? El pato se queda viudo.",
    "¿Cuál es el animal favorito de los atletas olímpicos? El loro.",
    "¿Sabes cómo le dicen a los deportistas en Veracruz? Aletas.",
    "¿Qué sonido hace una panadería cuando explota? PAAAN.",
    "¿Cuál es la fruta que sufre violencia doméstica? La papá yaa.",
    "¿Cuál es el número que no vende? El noventa.",
    "Le preguntaron a Jackie Chan sobre una dirección y contestó: ¡Jaaaaa!",
    "¿Sabes por qué los elefantes se pintan los huevos de rojo? Para esconderse en la mata de cerezas. ¿Has visto alguno? No. ¿Ves lo bien que se esconden?",
    "¿Te sabes el chiste del sordo y el distraído? —No. —¿Cómo?",
    "¿Cómo le dicen a un burro que vende sábanas? Un burrito sabanero.",
    "¿Dónde está la feria de Cepillín? En su cartera.",
    "El Temach si fuera un estómago: El stomach.",
    "Si el Temach fuera maestro de natación: ¡Mándela a la alberca, mi compa!",
    "Cuando le preguntas a tu amigo el DJ qué hay para beber: Agua agua agua xdd.",
    "¿Cuál es el colmo de Batman? Que lo Robin.",
    "Para ser Franco tendría que cambiarme el nombre.",
    "¿Saben por qué la ballena no se subió a la combi? Porque en el mar no hay combis.",
    "Un pato y un niño nacen a la vez, al cabo de un año ¿quién es mayor? El pato, porque tiene año y pico.",
    "A un gato le robaron su oro y ¿sabes qué dijo? MiAu miAu.",
    "¿Cómo murió? La golpearon con un violín, una guitarra y un bajo. Mmmm... todo concuerda.",
    "—¿Sabes qué me hace sonreír? —Awww ¿yo? —No, el nervio facial.",
    "¿Sabes cómo se llama el hermano perdido de Pinocho? Pinueve.",
    "Había un hombre tan pero tan fuerte que dobló la esquina.",
    "¿Sabes cuál es el árbol que asusta? El arbuuusto.",
    "¿Cómo se llaman las botas que se comen? Botanas.",
    "¿Qué le dijo una manzana a un cigarro? Nada porque no hablan.",
    "¿Qué le dijo una lata de atún a otra que estaba haciendo travesuras? Te voy a delatar.",
    "¿A dónde se van los billetes cansados? Al banco.",
    "¿Sabes por qué una jirafa toma más agua en marzo que en febrero? Porque marzo tiene más días.",
    "¿Qué le dijo un zapato travieso a otro? Ando desatado.",
    "¿Qué pasa si le pones maquillaje a un litro de gasolina? Se llamaría gasolinda.",
    "¿Por qué el pollo se arrojó al asador? Porque es el pollo loco.",
    "¿Cuál es el cable que te escucha? El de alta tensión.",
    "¿Por qué el caracol fue a la biblioteca? Porque está baboso.",
    "Una ardilla le dice a otra: A mí no me gustan las ardillas feas. —¡A chinga! ¿Por qué? —Es que me gustan las bellotas.",
    "¿Cómo le dice un libro a otro cuando salen de un problema? La libramos.",
    "¿Sabes por qué los golfistas usan dos pantalones? Por si tienen hoyo en uno.",
    "¿En qué se parece el tenis a Shrek? En que ambos tienen pelotas verdes.",
    "Si Batman es el caballero de la noche... ¿de día es un grosero?",
    "¿Qué hace un perro con un taladro? Ta-drando.",
    "¿Cómo se dice pañuelito en japonés? Sakamoko.",
    " Había un perro llamado Chiste. Vino un carro, lo pisó y se acabó el chiste.",
    "¿Qué le dijo un jaguar a otro jaguar? Jaguar yu?",
    "¿Qué hace una abeja en el gimnasio? Zum-ba.",
    "¿Qué le dice un pato a otro pato? Estamos empatados.",
    "¿Cómo se dice espejo en chino? Aitoyo.",
    "¿Qué hace una serpiente en el espacio? Sssss-tronauta.",
    "¿Qué le dijo una pared a otra pared? Nos vemos en la esquina.",
    "¿Por qué los pájaros no usan WhatsApp? Porque ya tienen Twitter.",
    "¿Qué hace un pez en la televisión? Nada.",
    "¿Cuál es el colmo de un jardinero? Que su novia se llame Rosa y lo deje plantado.",
    "¿Qué le dice un cero a otro cero? No somos nada.",
    "Había un hombre tan alto que comió un yogur y cuando le llegó al estómago ya estaba caducado.",
    "¿Qué le dice una cuchara a un tenedor? El cuchillo te anda buscando.",
    "¿Por qué los submarinos flotan? Porque no quieren irse al fondo de sus pensamientos.",
    "¿Qué le dijo un semáforo a otro? No me mires que me estoy cambiando.",
    "¿Cómo se llama el dinosaurio que duerme mucho? El Din-oso.",
    "¿Por qué las focas miran hacia arriba? Porque ahí están los focos.",
    "¿Qué le dice un cable de luz a otro? Estamos conectados.",
    "Había una vez un tomate en una carrera... y se quedó atrás porque no podía ketchup.",
    "¿Por qué la escoba está feliz? Porque va a la fiesta a barrer.",
    "¿Qué hace un huevo en el cine? Ver una película de yema.",
    "¿Por qué el libro de matemáticas lloraba? Porque tenía demasiados problemas.",
    "¿Qué le dice un paraguas a la lluvia? Me haces abrirme hacia ti.",
    "¿Cómo se dice disparo en árabe? Ahí-va-la-bala.",
    "¿Por qué las cebollas hacen llorar a la gente? Porque nadie las quiere comer solas.",
    "¿Qué hace una taza en el gimnasio? Ejercicios de asa.",
    "¿Por qué los esqueletos no pelean? Porque no tienen agallas.",
    "¿Qué le dice una uva verde a una morada? ¡Respira, tonta!",
    "¿Cómo se dice campesino en inglés? Campo-sation.",
    "¿Qué hace un gato cuando tiene hambre? Dice miau.",
    "¿Por qué los globos le tienen miedo a las agujas? Porque los dejan desinflados.",
    "¿Qué le dijo la luna al sol? Tan grande y no te dejan salir de noche.",
    "¿Cómo se llama el campeón de apnea japonés? Tokoshimo Fondo.",
    "¿Qué le dijo una chimenea a otra? Por aquí nos sale el humo.",
    "¿Por qué los patos no tienen deudas? Porque todo lo pagan al Cua-Cua.",
    "¿Qué le dice un plato a una taza? No te vayas a caer.",
    "¿Cómo se dice pelo sucio en chino? Chin champú.",
    "¿Qué hace un perro en el espacio? Buscar la Vía Láctea.",
    "¿Por qué los conejos son tan rápidos? Porque comen pura fibra.",
    "¿Qué le dice un semáforo a una persona? No me mires que estoy en rojo.",
    "¿Qué hace un gusano en la manzana? Dar una vuelta por el barrio.",
    "¿Por qué los elefantes no usan computadoras? Porque le tienen miedo al ratón.",
    "¿Qué le dijo un volcán a otro volcán? Me haces erupción.",
    "¿Cómo se llama el Santo de las computadoras? San Google.",
    "¿Qué hace una galleta en el mar? Se ablanda.",
    "¿Por qué los tigres no usan corbata? Porque no les entra en el cuello.",
    "¿Qué le dice una llave a un candado? Haces clic conmigo.",
    "¿Por qué los peces viven en el mar? Porque no tienen dinero para comprar casas.",
    "¿Qué hace un pingüino en una fiesta? Romper el hielo.",
    "¿Por qué las flores van a la escuela? Para aprender a florecer.",
    "¿Qué le dijo un árbol a otro? ¡Qué plantado estás!",
    "¿Cómo se dice náufrago en chino? Chinchancha.",
    "¿Qué hace un oso panda con una guitarra? Panda-rock.",
    "¿Por qué la luna es tan fría? Porque apaga el sol de noche.",
    "¿Qué le dice un foco a otro foco? Te veo muy brillante hoy.",
    "¿Por qué los caballos no usan tenis? Porque prefieren herraduras.",
    "¿Qué le dice un barco a otro barco? ¿Hace cuánto que no zarpas?",
    "¿Por qué el sol no va a la universidad? Porque ya tiene mil grados.",
    "¿Qué le dijo una manzana a otra en el árbol? Nos van a cosechar.",
    "¿Por qué los gatos siempre caen de pie? Porque tienen muy buen equilibrio.",
    "¿Qué le dice un billete a otro? Nos vemos en el banco.",
    "¿Por qué las ranas están tan contentas? Porque comen lo que les molesta.",
    "¿Qué hace una nube cuando tiene frío? Se pone a granizar.",
    "¿Por qué los caracoles no corren? Porque se les cae el techo.",
    "¿Qué le dice un tenedor a una cuchara? Eres muy profunda.",
    "¿Por qué los delfines andan felices? Porque nadan todo el día.",
    "¿Qué le dice un sol a la tierra? Me traes dando vueltas.",
    "¿Por qué el hielo flota? Porque no quiere irse al fondo.",
    "¿Qué le dice una dona a otra dona? Estás bien redondita.",
    "¿Por qué los perros mueven la cola? Porque la cola no puede mover al perro.",
    "¿Qué le dice un reloj a otro reloj? Nos vemos a la hora.",
    "¿Por qué las abejas trabajan tanto? Porque tienen una reina exigente.",
    "¿Qué le dice un río a otro río? Nos vemos en la desembocadura.",
    "¿Por qué los dinosaurios no tomaron café? Porque no tenían tazas gigantes.",
    "¿Qué le dice una estrella a otra estrella? Brillas bastante hoy.",
    "¿Por qué la paciencia es una virtud? Porque el café caliente tarda en enfriar.",
    "¿Qué le dice un botón a un ojal? Nos vemos al abrochar.",
    "¿Por qué las cebras tienen rayas? Para no equivocarse de pijama.",
    "¿Qué le dice un camión a otro camión? Nos vemos en el camino.",
    "¿Por qué los submarinos son oscuros? Para no llamar la atención en la profundidad.",
    "¿Qué le dice una linterna a la oscuridad? Se hizo la luz.",
    "¿Por qué los relojes hacen tic-tac? Porque si hicieran toc-toc parecerían puertas.",
    "¿Qué le dice un zapato al suelo? Te ando pisando constante.",
    "¿Por qué los peces no usan sombrero? Porque se les moja.",
    "¿Qué le dice un lápiz a la goma? Me borras las penas.",
    "¿Por qué las mariposas vuelan de flor en flor? Porque les gusta probar variedad.",
    "¿Qué le dijo la sartén al aceite? ¡Me estás chispeando!",
    "¿Por qué los pingüinos no van al desierto? Porque prefieren la nieve.",
    "¿Qué le dice la masa al horno? Nos vemos al dorar.",
    "¿Por qué el tomate se puso rojo? Porque vio la ensalada lista.",
    "¿Qué le dice una ventana a la brisa? Déjame entrar.",
    "¿Por qué los mosquitos cantan al oído? Porque les gusta la música cerca.",
    "¿Qué le dice la mantequilla al pan? Contigo me derrito.",
    "¿Por qué las estrellas parpadean? Porque les dio sueño.",
    "¿Qué le dice el café a la leche? Hacemos un buen equipo.",
    "¿Por qué los búhos duermen de día? Porque la noche es su fiesta.",
    "¿Qué le dice la sal a la comida? Te doy el toque.",
    "¿Por qué los puentes cruzan los ríos? Para llegar al otro lado.",
    "¿Qué le dice la esponja al agua? Absorbo todo de ti.",
    "¿Por qué las tortugas van lento? Porque disfrutan el paisaje.",
    "¿Qué le dice la azúcar al té? Te pongo dulce.",
    "¿Por qué el viento sopla? Porque no sabe chiflar.",
    "¿Qué le dice la tijera al papel? Nos vemos en el corte.",
    "¿Por qué el fuego brilla? Porque no sabe estar a oscuras.",
    "¿Qué le dice el peine al cabello? Te ando desenredando.",
    "¿Por qué el mar tiene olas? Para saludar a la playa.",
    "¿Qué le dice el zapato a la agujeta? Amárrame fuerte.",
    "¿Por qué la noche tiene luna? Para iluminar los sueños.",
    "¿Qué le dijo el despertador a la mañana? Es hora de levantarse.",
    "¿Por qué los grillos cantan de noche? Porque el escenario está libre.",
    "¿Qué le dice la sombra al cuerpo? Te sigo a todos lados.",
    "¿Por qué el río suena? Porque agua lleva.",
    "¿Qué le dice la cuchara a la sopa? Allá voy.",
    "¿Por qué el sol sale temprano? Porque le gusta la puntualidad.",
    "¿Qué le dijo el timbre a la puerta? Me presionas mucho.",
    "¿Por qué los pájaros madrugan? Para encontrar el mejor grano.",
    "¿Qué le dice la llanta al camino? Vámonos de viaje.",
    "¿Por qué el queso tiene hoyos? Para respirar mejor.",
    "¿Qué le dice el tenedor al plato? Acompaño la cena.",
    "¿Por qué las nubes viajan? Porque el viento las empuja.",
    "¿Qué le dice la brújula al viajero? Te marco el norte.",
    "¿Por qué la lluvia cae? Porque la gravedad manda.",
    "¿Qué le dice la llave al cerrojo? Entro con cuidado.",
    "¿Por qué las semillas germinan? Porque buscan la luz.",
    "¿Qué le dice el espejo a la sonrisa? Te reflejo al instante.",
    "¿Por qué las velas se consumen? Para dar su luz completa.",
    "¿Qué le dice el lápiz al papel? Voy a escribir una historia.",
    "¿Por qué los abrazos reconfortan? Porque transmiten calidez.",
    "¿Qué le dice la risa al buen café? Somos la mejor combinación en el Café de la Risa."
];
