<?php

return [
    "Un café entra al psicólogo y dice: Doctor, me siento muy molido.",
    "— Papá, ¿qué se siente tener un hijo tan inteligente? — No sé, hijo, pregúntale a tu abuelo.",
    "Le dije a mi jefe: Necesito un aumento, hay tres empresas detrás de mí. ¿Cuáles? La luz, el agua y el internet.",
    "Ayer me compré un reloj de pared y hoy me desperté colgado de la pared.",
    "¿Qué hace una abeja en el gimnasio? ¡Zum-ba!",
    "— Doctor, sufro de amnesia. — ¿Desde cuándo? — ¿Desde cuándo qué?",
    "¿Por qué los pájaros no usan celular? Porque ya tienen Twitter.",
    "¿Qué le dice un pez a otro pez? Nada.",
    "— Amor, me veo gorda? — Te ves hermosa. — Pero dime la verdad. — La verdad es que me da miedo responder.",
    "¿Qué le dice un jaguar a otro jaguar? Jaguar yu?",
    "— Doctor, ¿qué me recomienda para la memoria? — Que me pague la consulta antes de que se le olvide.",
    "Fui a comprar un libro de autoayuda y el vendedor no me quiso ayudar.",
    "¿Cómo se llama el campeón de buceo japonés? Tokoshimo Fondo.",
    "¿Qué le dice un techo a otro? Techo de menos.",
    "— Hola, ¿tienen pastillas para la flojera? — Sí. — Ponme dos en la boca, por favor.",
    "¿Por qué los esqueletos no pelean entre ellos? Porque no tienen agallas.",
    "— Cariño, dime algo hermoso. — El café de la mañana. — ¡Algo sobre mí! — Tú haciendo el café.",
    "¿Cómo saluda un vaquero a su hijo? ¡Hola, hijoooo!",
    "Me da risa la gente que ahorra para el futuro... ¡como si el futuro no fuera a llegar gratis!",
    "¿Qué le dice una impresora a otra? ¿Esa hoja es tuya o es impresión mía?",
    "Le pregunté a Siri: ¿Por qué estoy solo? Y me activó la cámara frontal.",
    "¿Qué le dice un semáforo a otro? No me mires que me estoy cambiando.",
    "El dinero no da la felicidad... pero prefiero llorar en un Mercedes.",
    "— Oye, ¿sabes hablar inglés? — Claro. — ¿Cómo se dice perro? — Dog. — ¿Y perrazo? — Big dog. — ¿Y perrísimo? — Doggy dog.",
    "¿Qué hace un perro con un látigo? Perreo duro.",
    "Ayer fui al cine y la película era tan mala que hasta los subtítulos se durmieron.",
    "¿Por qué el libro de matemáticas estaba triste? Porque tenía demasiados problemas.",
    "¿Qué le dice una serpiente a otra? ¿Somos venenosas? No sé, ¿por qué? ¡Porque me mordí la lengua!",
    "— Mi amor, ¿tienes algún secreto? — Sí, soy espía. — ¡No te creo! — ¿Ves? Por eso no le cuento nada a nadie.",
    "¿Qué le dice un número 3 al número 30? Para ser como yo tienes que ser sincero.",
    "Mi billetera es como una cebolla: abrirla me hace llorar.",
    "— Profe, ¿nos va a poner examen sorpresivo? — Sorpresivo sería que lo aprobaran.",
    "¿Qué hace un vampiro manejando una licuadora? Sangría.",
    "¿Cuál es el colmo de un electricista? Que su esposa se llame Luz y los hijos le le hagan corto circuito.",
    "Me encanta cocinar con vino... a veces hasta se lo echo a la comida.",
    "¿Qué le dice un fideo a otro en la olla? ¡Oye, mi cuerpo pide salsa!",
    "— ¿Cuánto cuesta este pastel? — $50. — ¿Y este otro? — $100. — ¿Por qué la diferencia? — Porque el de $100 es de chocolate y el de $50 es de fe.",
    "¿Por qué la gallina cruzó la carretera? Para demostrarle al pollo que sí se podía.",
    "Tengo tanta mala suerte que si me caigo de espaldas me rompo la nariz.",
    "¿Qué le dice un fantasma a otro? ¿Crees en los humanos?",
    "No soy perezoso, estoy en modo de ahorro de energía.",
    "— Doctor, veo doble. — Siéntense los dos en la camilla.",
    "¿Cómo se dice pañuelo en japonés? Sakamoko.",
    "¿Qué le dice una uva verde a una uva morada? ¡Respira, tonta!",
    "Hice una dieta de dos semanas y solo perdí 14 días.",
    "¿Qué le dice un gusano a otro? Voy a dar una vuelta a la manzana.",
    "— Oye, ¿qué te pasa? — Tuve un sueño feo con comida. — ¿Qué soñaste? — Que comía un plato de espaguetis gigantes y al despertar no encontraba mi cordón.",
    "¿Qué le dice una pared a otra? Nos vemos en la esquina.",
    "A los 20 años uno quiere cambiar el mundo. A los 30, solo quiere encontrar estacionamiento.",
    "¿Por qué las focas del circo miran hacia arriba? Porque ahí están los focos.",
    "— Papá, ¿hay fantasmas en la casa? — No hijo, ¿quién te dijo eso? — La sirvienta. — ¡Junta tus cosas, no tenemos sirvienta!",
    "Mi médico me dijo que dejara de cenar tarde. Ahora cenó a las 5:00 p.m. y vuelvo a cenar a las 11:00 p.m.",
    "¿Qué le dice una cuchara a un tenedor? El cuchillo te anda buscando.",
    "¿Por qué los patos no tienen deudas? Porque todo lo pagan al CUA-CUA.",
    "— ¿Cuál es tu plato favorito? — El hondo, porque cabe más comida.",
    "A veces quisiera ser un pulpo... para poder abofetear a 8 personas al mismo tiempo.",
    "¿Qué le dice un volcán a otro? Me haces erupción.",
    "— ¿Qué haces mirando la botella de agua? — Es que dice 'Concentrado'.",
    "¿Por qué el tomate no toma café? Porque se pone rojo.",
    "Tengo un metabolismo tan lento que si veo una foto de una pizza subo dos kilos.",
    "¿Qué le dice una taza a otra? ¿Qué taza haciendo?",
    "El trabajo duro nunca mató a nadie, pero ¿para qué arriesgarse?",
    "¿Cómo se llama el primo vegetariano de Bruce Lee? Broco Lee.",
    "La vida es corta... sonríe mientras todavía tengas dientes.",
    "¿Qué le dice una escoba a otra? Me tienes barrida de amor.",
    "Estoy en una forma increíble... 'Redonda' cuenta como forma, ¿no?",
    "¿Por qué los globos le tienen miedo a las agujas? Porque los dejan desinflados de risa.",
    "Mi cama y yo tenemos una relación perfecta, pero mi alarma está celosa.",
    "¿Qué hace un perro en el espacio? Buscar la Vía Láctea.",
    "— Papá, ¿es verdad que el dinero no compra la felicidad? — Sí hijo, pero da unos masajes buenísimos.",
    "¿Por qué los peces viven en agua salada? Porque la pimienta los hace estornudar.",
    "Si la montaña viene hacia ti... ¡corre, es un derrumbe!",
    "¿Qué le dice un cable a otro? ¡Estamos conectados!",
    "Mi planta favorita es el cactus... porque se cuida solo como yo en fin de semana.",
    "¿Qué hace un tomate en una carrera? Intenta ketchup-ar al de adelante.",
    "No estoy gordo, estoy lleno de amor y carbohidratos.",
    "¿Qué le dice una piedra a otra? La vida es dura.",
    "— Amor, ¿me compras un carro? — ¿Y la bici que te compré? — Ya no rueda bien. — ¡Pues pedaléale más fuerte!",
    "¿Cómo se dice disparo en árabe? Ahí-va-la-bala.",
    "Fui al gimnasio 3 días seguidos y no bajé de peso... creo que la caminadora estaba descalibrada.",
    "¿Qué le dice un zapato a otro? ¡Qué vida tan arrastrada llevamos!",
    "No necesito un estilista, mi almohada me despeina gratis cada mañana.",
    "¿Por qué los pulpos son tan buenos en las matemáticas? Porque tienen ocho tentáculos para contar.",
    "— Doctor, ¿el café es malo para los nervios? — No, lo malo es no tener café cuando estás nervioso.",
    "¿Qué le dice una bombilla a otra? Nos tienen entre la luz y la sombra.",
    "Decidí seguir mis sueños... así que me volví a acostar.",
    "¿Qué hace un lápiz en el gimnasio? Ejercicios de trazo.",
    "Mi billetera y mi estómago tienen un acuerdo: uno está vacío y el otro no se llena.",
    "¿Por qué las cebollas hacen llorar? Porque se dan cuenta de que nadie las quiere solas.",
    "Si el trabajo dignifica... ¿por qué todos sueñan con la jubilación?",
    "¿Qué le dice un pastel a otro? Nos vemos en el cumple.",
    "Amo el café porque me da la ilusión de estar despierto.",
    "¿Por qué los pingüinos no van al cine en verano? Porque se les derrite la palomita.",
    "— ¿Tienes agua bendita? — No, pero tengo café caliente que revive muertos.",
    "¿Qué le dice una puerta a otra? ¿Quién toca?",
    "Tengo tantos proyectos que hasta el lunes me da flojera empezar.",
    "¿Qué hace un pingüino en una discoteca? Romper el hielo.",
    "Si te caes 7 veces, levántate 8... pero a la novena pide un café.",
    "¿Qué le dice un peine a un calvo? Te echo de menos.",
    "El único ejercicio que hago es correr riesgos.",
    "¿Por qué la luna es tan fría? Porque apaga el sol de noche.",
    "¿Qué le dice un foco a otro? Te veo muy brillante hoy.",
    "Mi comida favorita es cualquier cosa que no tenga que cocinar yo.",
    "¿Qué le dice un barco a otro? ¿Hace cuánto que no zarpas?",
    "Si el amor es ciego... ¿por qué la lencería es tan popular?",
    "¿Qué hace una galleta en la piscina? Se ablanda.",
    "El café no resuelve los problemas, pero tampoco lo hace el agua y al menos sabe rico.",
    "¿Por qué los gatos siempre ganan al escondite? Porque son muy sigilosos.",
    "No me despiertes si no hay café recién hecho.",
    "¿Qué le dice un paraguas a la lluvia? Me haces abrirme hacia ti.",
    "La vida sin café es como un celular sin batería.",
    "¿Qué hace un pez en el cine? Ver películas de agua.",
    "Si la práctica hace al maestro... yo ya debería ser cinturón negro en comer tacos.",
    "¿Por qué los tigres no usan corbata? Porque no les entra al cuello.",
    "Un día sin café es... mentira, no sé qué es eso, nunca lo he intentado.",
    "¿Qué le dice un libro a otro libro? Nos leemos luego.",
    "No soy dormilón, soy un apasionado de los sueños.",
    "¿Por qué las flores van a la escuela? Para aprender a florecer.",
    "El dinero no te da amigos, pero te da una clase de enemigos mejor vestida.",
    "¿Qué hace un oso panda con una guitarra? Panda-rock.",
    "El café de la mañana es la única razón por la que no le hablo feo a las mañanas.",
    "¿Por qué el sol no va a la universidad? Porque ya tiene mil grados.",
    "Mi pasatiempo favorito es contar las horas para volver a dormir.",
    "¿Qué le dice una llave a un candado? Haces clic en mi vida.",
    "Si comer fuera un deporte, tendría medalla de oro olímpica.",
    "¿Por qué los delfines son tan simpáticos? Porque siempre andan sonriendo en el mar.",
    "Un buen café soluciona lo que 8 horas de sueño arruinaron.",
    "¿Qué le dice un árbol a otro? ¡Qué plantado estás!",
    "No hay problema que un capuchino con espuma no pueda suavizar.",
    "¿Por qué los elefantes no usan computadoras? Porque le tienen miedo al ratón.",
    "Mi nivel de energía mañanero depende directamente de la cafeína en mi sangre.",
    "¿Qué le dice un globo a otro en una fiesta? ¡Estás que revientas!",
    "La paciencia es la virtud de esperar a que el café se enfríe un poco.",
    "¿Por qué el mar es azul? Porque los peces hacen 'blue blue'.",
    "Si la vida te da limones... pide tequila y sal.",
    "¿Qué hace un astronauta si tiene frío? Se pone un traje espacial calefaccionado.",
    "El café es el mejor invento después del botón de posponer la alarma.",
    "¿Por qué las mariposas vuelan tan suave? Porque no llevan prisa.",
    "Mi pasatiempo de fin de semana es respirar hondo y tomar café.",
    "¿Qué le dice una manzana a otra? ¡Nos van a hacer jugo!",
    "El único drama que acepto en mi vida es la espuma de mi café.",
    "¿Por qué los conejos son tan rápidos? Porque comen pura fibra.",
    "Si no vas a sumar en mi vida, al menos tráeme un café.",
    "¿Qué le dice un río a otro? Nos vemos en el mar.",
    "La risa es el mejor remedio... después de un buen expreso doble.",
    "¿Por qué los dinosaurios no tomaban café? Porque no tenían tazas gigantes.",
    "Un café caliente cura cualquier corazón frío.",
    "¿Qué le dice una dona a otra? Estás bien redondita.",
    "La vida empieza después del primer sorbo de café.",
    "¿Por qué los perros mueven la cola? Porque la cola no puede mover al perro.",
    "Un día perfecto se mide en tazas de café y sonrisas.",
    "¿Qué le dice un reloj a otro? Nos vemos a la hora.",
    "El café es un abrazo líquido para el cerebro.",
    "¿Por qué el hielo flota? Porque no quiere ahogarse.",
    "Si el café fuera legal en los exámenes, todos sacarían 100.",
    "¿Qué le dice un tenedor a una cuchara? ¡Eres muy profunda!",
    "No necesito una varita mágica, necesito una cafetera llena.",
    "¿Por qué los osos duermen todo el invierno? Porque no descubrieron el café.",
    "Sonreír es gratis, pero acompañarlo con café es un lujo.",
    "¿Qué le dice una estrella a otra? ¡Brillas bastante hoy!",
    "El café: combustible oficial de los sobrevivientes de la semana.",
    "¿Por qué las ranas están tan felices? Porque comen lo que les molesta.",
    "Si la felicidad tuviera aroma, olería a granos de café tostado.",
    "¿Qué le dice una montaña a otra? ¡Qué cumbre tan alta!",
    "El café es la respuesta, no importa cuál sea la pregunta.",
    "¿Por qué los caballos no usan zapatos deportivos? Porque prefieren herraduras.",
    "Un trago de café y de repente el mundo tiene sentido.",
    "¿Qué le dice un billete a otro? Nos vemos en el banco.",
    "La vida es demasiado corta para tomar café malo.",
    "¿Por qué los caracoles no corren? Porque se les cae la casa.",
    "El café: convirtiendo 'déjame en paz' en 'buenos días' desde tiempos inmemoriales.",
    "¿Qué le dice una nube a otra? Nos vemos abajo si llueve.",
    "El ingrediente secreto del éxito es una taza de café recién cargado.",
    "¿Por qué las aves cantan al amanecer? Porque están felices de que salió el sol.",
    "Un suspiro y un sorbo de café: la mejor combinación del día.",
    "¿Qué le dice un plato a una taza? ¡No te caigas!",
    "El café no hace milagros, pero hace que las mañanas parezcan uno.",
    "¿Por qué las abejas trabajan tanto? Porque tienen una reina exigente.",
    "Nada une más a las personas que un café con una buena plática.",
    "¿Qué le dice un sol a la tierra? ¡Me traes dando vueltas!",
    "El mejor momento para tomar café es AHORA.",
    "¿Por qué los koalas duermen tanto? Porque son muy tranquilos.",
    "Una sonrisa y un café son las dos mejores formas de empezar la jornada.",
    "¿Qué le dice un botón a un ojal? Nos vemos al abrochar.",
    "El aroma del café es la música del olfato.",
    "¿Por qué los leones son reyes? Porque nadie se atreve a discutirles.",
    "El café es paz en taza.",
    "¿Qué le dice un camión a otro? ¡Nos vemos en la carretera!",
    "Con fe y con café, todo se puede.",
    "¿Por qué las cebras tienen rayas? Para no confundirse de pijama.",
    "Un buen café y una buena risa: la receta del Café de la Risa."
];
